2021-03-04 19:16:23,095 :: client.py:59 :: INFO :: Done with config initialization
2021-03-04 19:16:23,100 :: client.py:388 :: INFO :: Started server successfully at address: ('127.0.1.1', 24317)
2021-03-04 19:16:31,047 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x04' to ('127.0.1.1', 7672)
2021-03-04 19:16:31,469 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:31,515 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:31,608 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:31,656 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:33,060 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:33,076 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:33,216 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:16:33,247 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:34,748 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:34,780 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:34,903 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:34,935 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:36,283 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:36,284 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:36,439 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:16:36,470 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:38,155 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:16:38,186 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:38,328 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:16:38,342 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:39,702 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:16:39,750 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:16:39,762 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/4.txt
2021-03-04 19:16:39,779 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:39,963 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,031 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,213 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/4.txt
2021-03-04 19:16:40,228 :: client.py:308 :: INFO :: Request for 4 from 7672 completed successfully.
2021-03-04 19:18:57,639 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x02' to ('127.0.1.1', 7672)
2021-03-04 19:18:57,733 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:18:57,780 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:18:57,796 :: client.py:219 :: INFO :: Connection complete after receiving file from ('127.0.1.1', 7672)
2021-03-04 19:18:57,796 :: client.py:118 :: INFO :: Empty file detected: configs/clients/2/downloads/2.txt
2021-03-04 19:18:57,842 :: client.py:308 :: INFO :: Request for 2 from 7672 completed successfully.
2021-03-04 19:19:49,328 :: client.py:340 :: INFO :: Sent data: b'\x00\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:49,686 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:49,733 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:49,826 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:49,874 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:51,449 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:51,497 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:51,608 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:19:51,655 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:53,217 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:53,264 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:53,404 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:53,404 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:54,998 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:55,045 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:55,170 :: client.py:348 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:19:55,218 :: client.py:340 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:56,686 :: client.py:348 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:19:56,718 :: client.py:340 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:56,937 :: client.py:348 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:19:56,984 :: client.py:340 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:58,746 :: client.py:348 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:19:58,793 :: client.py:340 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7951)
2021-03-04 19:19:58,825 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/1.txt
2021-03-04 19:19:58,840 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,292 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,575 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,906 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/1.txt
2021-03-04 19:19:59,952 :: client.py:308 :: INFO :: Request for 1 from 7951 completed successfully.
2021-03-04 19:21:59,955 :: client.py:59 :: INFO :: Done with config initialization
2021-03-04 19:21:59,960 :: client.py:391 :: INFO :: Started server successfully at address: ('127.0.1.1', 24317)
2021-03-04 19:23:07,124 :: client.py:343 :: INFO :: Sent data: b'\x00\x00\x04' to ('127.0.1.1', 7672)
2021-03-04 19:23:07,482 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:07,528 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:07,621 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:07,669 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:08,280 :: client.py:423 :: INFO :: New connection request from ('127.0.0.1', 57100) for file 0
2021-03-04 19:23:08,372 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-04 19:23:08,750 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:08,875 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:09,046 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:09,047 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:09,108 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:09,125 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:09,218 :: client.py:351 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:23:09,249 :: client.py:343 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:09,357 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:09,371 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:10,469 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:10,531 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:10,562 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:10,625 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:10,625 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:10,703 :: client.py:552 :: INFO :: Sent data with seq 3
2021-03-04 19:23:10,703 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:10,811 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:10,920 :: client.py:575 :: INFO :: deleting 2
2021-03-04 19:23:10,966 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 3
2021-03-04 19:23:10,982 :: client.py:575 :: INFO :: deleting 3
2021-03-04 19:23:12,046 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:12,062 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:12,093 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:12,125 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:12,170 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:12,171 :: client.py:351 :: INFO :: Sent ACK for seq: 3
2021-03-04 19:23:12,185 :: client.py:343 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:12,265 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:12,437 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:12,532 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:12,548 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:13,638 :: client.py:351 :: INFO :: Sent ACK for seq: 0
2021-03-04 19:23:13,671 :: client.py:343 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:13,639 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:13,733 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:13,811 :: client.py:351 :: INFO :: Sent ACK for seq: 1
2021-03-04 19:23:13,826 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:13,858 :: client.py:343 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:13,906 :: client.py:552 :: INFO :: Sent data with seq 3
2021-03-04 19:23:14,108 :: client.py:575 :: INFO :: deleting 2
2021-03-04 19:23:14,233 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 3
2021-03-04 19:23:14,233 :: client.py:575 :: INFO :: deleting 3
2021-03-04 19:23:15,273 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:15,273 :: client.py:351 :: INFO :: Sent ACK for seq: 2
2021-03-04 19:23:15,304 :: client.py:552 :: INFO :: Sent data with seq 0
2021-03-04 19:23:15,304 :: client.py:343 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 7672)
2021-03-04 19:23:15,310 :: /mnt/d/SocketProg/PyTorrent/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,311 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,326 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 0
2021-03-04 19:23:15,375 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,376 :: /mnt/d/SocketProg/PyTorrent/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,395 :: client.py:123 :: INFO :: File hash verified: configs/clients/2/downloads/4.txt
2021-03-04 19:23:15,406 :: client.py:311 :: INFO :: Request for 4 from 7672 completed successfully.
2021-03-04 19:23:15,406 :: client.py:552 :: INFO :: Sent data with seq 1
2021-03-04 19:23:15,605 :: client.py:575 :: INFO :: deleting 0
2021-03-04 19:23:15,657 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 1
2021-03-04 19:23:15,673 :: client.py:575 :: INFO :: deleting 1
2021-03-04 19:23:16,719 :: client.py:625 :: WARNING :: Resend called for ('127.0.0.1', 57100) as no ack received. Retry count: 10
2021-03-04 19:23:16,766 :: client.py:552 :: INFO :: Sent data with seq 2
2021-03-04 19:23:16,829 :: client.py:460 :: INFO :: Received ACK from ('127.0.0.1', 57100) for seq_no: 2
2021-03-04 19:23:16,909 :: client.py:575 :: INFO :: deleting 2
2021-03-11 16:00:43,499 :: ./client/client.py:40 :: INFO :: Done with config initialization
2021-03-11 16:06:00,570 :: ./client/client.py:40 :: INFO :: Done with config initialization
2021-03-11 16:06:00,572 :: /home/arun/PyTorrent/client/p2p.py:91 :: INFO :: Started server successfully at address: ('127.0.1.1', 21770)
2021-03-11 16:11:22,223 :: ./client/client.py:40 :: INFO :: Done with config initialization
2021-03-11 16:11:22,225 :: /home/arun/PyTorrent/client/p2p.py:91 :: INFO :: Started server successfully at address: ('127.0.1.1', 21770)
2021-03-11 16:11:37,937 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 43738) for file 3
2021-03-11 16:11:37,957 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/3.txt
2021-03-11 16:11:38,100 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:38,220 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:38,356 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 0
2021-03-11 16:11:38,361 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:38,392 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 1
2021-03-11 16:11:38,397 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:39,422 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 43738) as no ack received. Retry count: 10
2021-03-11 16:11:39,438 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:39,463 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 2
2021-03-11 16:11:39,558 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:11:39,694 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:11:39,740 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 3
2021-03-11 16:11:39,745 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:11:40,761 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 43738) as no ack received. Retry count: 10
2021-03-11 16:11:40,776 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:40,801 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 0
2021-03-11 16:11:40,897 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:41,038 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:41,073 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 1
2021-03-11 16:11:41,079 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:42,109 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 43738) as no ack received. Retry count: 10
2021-03-11 16:11:42,119 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:42,145 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 2
2021-03-11 16:11:42,240 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:11:42,376 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:11:42,416 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 3
2021-03-11 16:11:42,422 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:11:43,442 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 43738) as no ack received. Retry count: 10
2021-03-11 16:11:43,457 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:43,483 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 0
2021-03-11 16:11:43,573 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:43,709 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:43,749 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 1
2021-03-11 16:11:43,755 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:44,775 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 43738) as no ack received. Retry count: 10
2021-03-11 16:11:44,790 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:44,811 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 43738) for seq_no: 2
2021-03-11 16:11:44,931 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:11:51,314 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 36188) for file 10
2021-03-11 16:11:51,339 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/10.txt
2021-03-11 16:11:51,486 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:51,607 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:51,748 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 0
2021-03-11 16:11:51,753 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:51,789 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 1
2021-03-11 16:11:51,794 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:52,819 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 36188) as no ack received. Retry count: 10
2021-03-11 16:11:52,830 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:52,850 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 2
2021-03-11 16:11:52,945 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:11:53,081 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:11:53,127 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 3
2021-03-11 16:11:53,132 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:11:54,147 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 36188) as no ack received. Retry count: 10
2021-03-11 16:11:54,157 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:54,178 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 0
2021-03-11 16:11:54,278 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:54,419 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:54,459 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 1
2021-03-11 16:11:54,465 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:55,480 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 36188) as no ack received. Retry count: 10
2021-03-11 16:11:55,495 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:55,521 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 2
2021-03-11 16:11:55,616 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:11:55,757 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:11:55,793 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 3
2021-03-11 16:11:55,799 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:11:56,829 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 36188) as no ack received. Retry count: 10
2021-03-11 16:11:56,840 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:11:56,865 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 0
2021-03-11 16:11:56,950 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:11:57,091 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:11:57,132 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 1
2021-03-11 16:11:57,137 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:11:58,152 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 36188) as no ack received. Retry count: 10
2021-03-11 16:11:58,162 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:11:58,188 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 36188) for seq_no: 2
2021-03-11 16:11:58,298 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:12:04,549 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x00\x00\x00' to ('127.0.1.1', 28970)
2021-03-11 16:12:04,727 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 0
2021-03-11 16:12:04,743 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:04,848 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 1
2021-03-11 16:12:04,863 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:06,065 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 2
2021-03-11 16:12:06,081 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:06,186 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 3
2021-03-11 16:12:06,201 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:07,399 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 0
2021-03-11 16:12:07,409 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:07,514 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 1
2021-03-11 16:12:07,529 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:09,090 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 2
2021-03-11 16:12:09,106 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:09,211 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 3
2021-03-11 16:12:09,226 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x03\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:10,490 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 0
2021-03-11 16:12:10,505 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x00\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:10,605 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 1
2021-03-11 16:12:10,621 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x01\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:10,923 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 35157) for file 10
2021-03-11 16:12:10,938 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/10.txt
2021-03-11 16:12:11,070 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:12:11,180 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:12:11,326 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 0
2021-03-11 16:12:11,332 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:12:11,357 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 1
2021-03-11 16:12:11,362 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:12:11,869 :: /home/arun/PyTorrent/client/p2p.py:51 :: INFO :: Sent ACK for seq: 2
2021-03-11 16:12:11,884 :: /home/arun/PyTorrent/client/p2p.py:43 :: INFO :: Sent data: b'\x02\x01' to ('127.0.1.1', 28970)
2021-03-11 16:12:11,895 :: /home/arun/PyTorrent/utils/utils.py:42 :: INFO :: Verify hash of file configs/clients/2/downloads/0.txt.txt
2021-03-11 16:12:11,900 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/0.txt.txt
2021-03-11 16:12:12,037 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/0.txt.txt
2021-03-11 16:12:12,164 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/downloads/0.txt.txt
2021-03-11 16:12:12,286 :: ./client/client.py:127 :: INFO :: File deleted: configs/clients/2/downloads/0.txt.txt due to failed hash check
2021-03-11 16:12:12,312 :: ./client/client.py:322 :: INFO :: Request for 0.txt from  28970 completed successfully.
2021-03-11 16:12:12,393 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 35157) as no ack received. Retry count: 10
2021-03-11 16:12:12,408 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:12:12,434 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 2
2021-03-11 16:12:12,524 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:12:12,659 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:12:12,705 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 3
2021-03-11 16:12:12,710 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:12:13,741 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 35157) as no ack received. Retry count: 10
2021-03-11 16:12:13,766 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:12:13,782 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 0
2021-03-11 16:12:13,882 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:12:14,017 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:12:14,063 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 1
2021-03-11 16:12:14,068 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:12:15,094 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 35157) as no ack received. Retry count: 10
2021-03-11 16:12:15,109 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:12:15,130 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 2
2021-03-11 16:12:15,225 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 16:12:15,360 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 16:12:15,401 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 3
2021-03-11 16:12:15,406 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 16:12:16,427 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 35157) as no ack received. Retry count: 10
2021-03-11 16:12:16,442 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 16:12:16,468 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 0
2021-03-11 16:12:16,563 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 16:12:16,698 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 16:12:16,749 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 1
2021-03-11 16:12:16,754 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 16:12:17,775 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 35157) as no ack received. Retry count: 10
2021-03-11 16:12:17,790 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 16:12:17,816 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 35157) for seq_no: 2
2021-03-11 16:12:17,931 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:45:01,122 :: client/client.py:40 :: INFO :: Done with config initialization
2021-03-11 18:45:01,124 :: /home/arun/PyTorrent/client/p2p.py:91 :: INFO :: Started server successfully at address: ('127.0.1.1', 21770)
2021-03-11 18:45:27,305 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 59149) for file 3
2021-03-11 18:45:27,321 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/3.txt
2021-03-11 18:45:27,464 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:45:27,585 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:45:27,716 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 0
2021-03-11 18:45:27,721 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:45:27,741 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 1
2021-03-11 18:45:27,747 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:45:28,768 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 59149) as no ack received. Retry count: 10
2021-03-11 18:45:28,788 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:45:28,814 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 2
2021-03-11 18:45:28,909 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 18:45:29,030 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:45:29,051 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 3
2021-03-11 18:45:29,056 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 18:45:30,087 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 59149) as no ack received. Retry count: 10
2021-03-11 18:45:30,102 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:45:30,123 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 0
2021-03-11 18:45:30,213 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:45:30,349 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:45:30,395 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 1
2021-03-11 18:45:30,400 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:45:31,426 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 59149) as no ack received. Retry count: 10
2021-03-11 18:45:31,431 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:45:31,447 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 2
2021-03-11 18:45:31,547 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 18:45:31,673 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:45:31,709 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 3
2021-03-11 18:45:31,714 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 18:45:32,735 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 59149) as no ack received. Retry count: 10
2021-03-11 18:45:32,755 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:45:32,771 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 0
2021-03-11 18:45:32,876 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:45:33,002 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:45:33,043 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 1
2021-03-11 18:45:33,048 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:45:34,064 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 59149) as no ack received. Retry count: 10
2021-03-11 18:45:34,085 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:45:34,110 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 59149) for seq_no: 2
2021-03-11 18:45:34,210 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:50:19,949 :: client/client.py:40 :: INFO :: Done with config initialization
2021-03-11 18:50:19,954 :: /home/arun/PyTorrent/client/p2p.py:91 :: INFO :: Started server successfully at address: ('127.0.1.1', 21770)
2021-03-11 18:50:25,361 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 49618) for file 0
2021-03-11 18:50:25,377 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-11 18:50:25,428 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:50:25,543 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:50:25,674 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 49618) for seq_no: 0
2021-03-11 18:50:25,680 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:50:25,695 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 49618) for seq_no: 1
2021-03-11 18:50:25,705 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:50:58,872 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 60596) for file 0
2021-03-11 18:50:58,878 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-11 18:50:58,878 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:50:58,998 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:50:59,145 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60596) for seq_no: 0
2021-03-11 18:50:59,150 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:50:59,170 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60596) for seq_no: 1
2021-03-11 18:50:59,175 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:51:22,136 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 54682) for file 0
2021-03-11 18:51:22,151 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-11 18:51:22,208 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:51:22,328 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:51:22,465 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 54682) for seq_no: 0
2021-03-11 18:51:22,470 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:51:22,491 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 54682) for seq_no: 1
2021-03-11 18:51:22,496 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:51:52,061 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 40636) for file 0
2021-03-11 18:51:52,066 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-11 18:51:52,066 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:51:52,187 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:51:52,307 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 40636) for seq_no: 0
2021-03-11 18:51:52,308 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:51:52,333 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 40636) for seq_no: 1
2021-03-11 18:51:52,339 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:56:26,330 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 47232) for file 0
2021-03-11 18:56:26,336 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/0.txt
2021-03-11 18:56:26,336 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:56:26,456 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:56:26,598 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 47232) for seq_no: 0
2021-03-11 18:56:26,603 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:56:26,623 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 47232) for seq_no: 1
2021-03-11 18:56:26,629 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:57:21,061 :: /home/arun/PyTorrent/client/p2p.py:123 :: INFO :: New connection request from ('127.0.0.1', 60953) for file 7
2021-03-11 18:57:21,071 :: /home/arun/PyTorrent/utils/utils.py:31 :: INFO :: Get hash of configs/clients/2/7.txt
2021-03-11 18:57:21,220 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:57:21,341 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:57:21,477 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 0
2021-03-11 18:57:21,482 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:57:21,512 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 1
2021-03-11 18:57:21,517 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:57:22,538 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 60953) as no ack received. Retry count: 10
2021-03-11 18:57:22,544 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:57:22,574 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 2
2021-03-11 18:57:22,664 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 18:57:22,795 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:57:22,806 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 3
2021-03-11 18:57:22,806 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 18:57:23,817 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 60953) as no ack received. Retry count: 10
2021-03-11 18:57:23,837 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:57:23,863 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 0
2021-03-11 18:57:23,958 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:57:24,094 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:57:24,125 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 1
2021-03-11 18:57:24,131 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:57:25,151 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 60953) as no ack received. Retry count: 10
2021-03-11 18:57:25,172 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:57:25,198 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 2
2021-03-11 18:57:25,293 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 3
2021-03-11 18:57:25,429 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
2021-03-11 18:57:25,455 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 3
2021-03-11 18:57:25,460 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 3
2021-03-11 18:57:26,481 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 60953) as no ack received. Retry count: 10
2021-03-11 18:57:26,491 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 0
2021-03-11 18:57:26,517 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 0
2021-03-11 18:57:26,607 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 1
2021-03-11 18:57:26,723 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 0
2021-03-11 18:57:26,754 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 1
2021-03-11 18:57:26,759 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 1
2021-03-11 18:57:27,770 :: /home/arun/PyTorrent/client/p2p.py:324 :: WARNING :: Resend called for ('127.0.0.1', 60953) as no ack received. Retry count: 10
2021-03-11 18:57:27,775 :: /home/arun/PyTorrent/client/p2p.py:252 :: INFO :: Sent data with seq 2
2021-03-11 18:57:27,796 :: /home/arun/PyTorrent/client/p2p.py:160 :: INFO :: Received ACK from ('127.0.0.1', 60953) for seq_no: 2
2021-03-11 18:57:27,906 :: /home/arun/PyTorrent/client/p2p.py:275 :: INFO :: deleting 2
